#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor DP-2 -d I II III IV V
# bspc monitor DP-0 -d VI VII VIII IX X

$HOME/.config/wm_scripts/get-monitors.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
bspc config border_width 0

picom & 
feh --bg-fill ~/Desktop/wallpapers/great-wave.png
clipit &
xset dpms 0 0 0 &
xset s off &

$HOME/.config/polybar/launch.sh
